### PR TITLE
Adds pandas `contrib` module

### PR DESCRIPTION
**Pull request by Nollde**
These changes add the pandas `contrib` module.
For now this `contrib` module includes the `DataFrameFormatter`.
The `DataFrameFormatter` can be used to read and write instances of `pandas.DataFrame`.

### CODE REVIEW

**Comment by Nollde** [comment]
I am very open to discuss if we want a default `key` when using `pandas.DataFrame.to_hdf`

**Comment by riga** [comment]
Looks good, thanks!

**Comment by riga** [comment]
@Nollde After further review, I think we should change the `name` class attribute of the formatter to something less generic. Other libraries (spark, root, ...) have their own interpretation of "data frames", so I would suggest `dataframe` -> `pandas` or `pandas_dataframe`.

**Comment by riga** [comment]
Changed in [ca4e237](https://github.com/riga/law/commit/ca4e2375f4f05702ed21091ef7704410a3bcf976) for the upcoming 0.1.19 release.

**Pull request merged**
